((nil . ((indent-tabs-mode . nil)
         (c-basic-offset . 4)
         (cmake-ide-build-dir . "~/code/github/marian-debug")
         (compile-command . "cd ~/code/github/marian-debug && make")
         (projectile-project-compilation-cmd . "cd ~/code/github/marian-debug && make")
         (projectile-project-test-cmd . "cd ~/code/github/marian-debug && make test")
         (projectile-project-run-cmd . "cd ~/code/github/marian-debug && ./marian_d")
         )))
